/**
 * Старые id товаров мок-каталога прототипа ("p-atlant") -> slug. Нужны только для миграции
 * localStorage (корзина, избранное, заказы), сохранённого до перехода на Payload (SH-CART).
 * ponytail: таблица заморожена; удалить, когда старых данных в браузерах не останется.
 */
export const LEGACY_PRODUCT_IDS: Record<string, string> = {
  "p-fenix": "feniks",
  "p-fenix-lite": "feniks-layt",
  "p-prometey": "prometey",
  "p-optima": "optima",
  "p-universal": "universal",
  "p-standart": "standart",
  "p-standart-plus": "standart-plyus",
  "p-atlant": "atlant",
  "p-atlant-2": "atlant-2-sloy",
  "p-lux": "lyuks",
  "p-lux-max": "lyuks-maks",
  "p-atlant-plus": "atlant-plyus",
  "p-atlant-2-plus": "atlant-2-sloy-plyus",
  "p-malahit": "malahit",
  "p-yashma": "yashma",
  "p-yashma-lux": "yashma-lyuks",
  "p-profi-micro": "profi-mikrotochka",
  "p-profi-vl": "profi-vl-3-4",
  "p-profi-vl-strong": "profi-vl-3-4-strong",
  "p-profi-rl": "profi-rl-1-2",
  "p-profi-s-vl": "profi-s-vl-3-4",
  "p-profi-strong-gn": "profi-strong-gn-3-4",
  "p-profi-pu": "profi-pu-1-2",
  "p-profi-khaki": "profi-khaki-rl-3-4",
  "p-profi-gn": "profi-gn-1-2",
  "p-profi-lite": "profi-layt",
  "p-hvat": "hvat-hb-rl-1-2",
  "p-hvat-12": "hvat-hb-rl-1-2-standart",
  "p-hvat-34": "hvat-hb-rl-3-4",
  "p-cut": "antiporez-pu-1-2",
  "p-floragrip": "floragrip",
  "p-floragrip-lite": "floragrip-layt",
  "p-frost": "frost-strong-vl-3-4",
  "p-frost-lux": "frostlyuks-vl-3-4",
  "p-frost-lite": "frostlayt-1-2",
  "p-frost-rl": "frost-rl-1-2",
  "p-frost-vl": "frost-vl-3-4",
  "p-frost-strong-lux": "frost-stronglyuks-vl-3-4",
  "p-frost-palm": "frost-palm-vl-3-4",
  "p-fleece": "frost-flis",
  "p-shield": "zevs-shchit-sk",
  "p-shield-sm": "zevs-shchit-sm",
  "p-shield-lite": "zevs-shchit-layt",
  "p-strongshell": "strongshell-cbc",
  "p-shield-km": "zevs-shchit-km",
  "p-oilmax": "oilresist-maks",
  "p-kshs": "zashchita-import-kshs-t1",
  "p-kshs-t2": "zashchita-import-kshs-t2",
  "p-gloves": "gloves-hoz",
  "p-lotus": "lotos-hoz",
  "p-manual": "manual-smotr",
  "p-crystal": "crystal-xp",
  "p-kragi-lux": "zevs-trk-lyuks",
  "p-kragi-kevlar": "zevs-sb",
  "p-kragi-krs": "zevs-krs",
  "p-kragi-spf": "zevs-spf",
  "p-kragi-spf-lux": "zevs-spf-lyuks",
  "p-driver": "zevs-drv",
  "p-docker": "zevs-dkr",
  "p-ruk-brez": "ruk-dv-br",
  "p-ruk-hb-brez": "ruk-hb-brez-400",
  "p-ruk-od": "ruk-od420-200",
  "p-ruk-pvh": "ruk-hb-pvh-500",
  "p-ruk-vat": "ruk-hb-vat-100",
  "p-ruk-suk": "ruk-suk-100",
};

/** slug по старому id; уже-slug и неизвестные — undefined. */
export function legacySlug(id: string): string | undefined {
  return Object.hasOwn(LEGACY_PRODUCT_IDS, id) ? LEGACY_PRODUCT_IDS[id] : undefined;
}
