/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    customers: Customer;
    categories: Category;
    products: Product;
    media: Media;
    reviews: Review;
    orders: Order;
    leads: Lead;
    'post-categories': PostCategory;
    posts: Post;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'post-categories': PostCategoriesSelect<false> | PostCategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    about: About;
    delivery: Delivery;
    navigation: Navigation;
    settings: Setting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    delivery: DeliverySelect<false> | DeliverySelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: {
      'b24-sync': TaskB24Sync;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'manager' | 'content';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  kind?: ('person' | 'legal') | null;
  name: string;
  phone?: string | null;
  company?: string | null;
  inn?: string | null;
  kpp?: string | null;
  address?: string | null;
  addresses?:
    | {
        label: string;
        city: string;
        line: string;
        phone?: string | null;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  bankName?: string | null;
  bankAccount?: string | null;
  bik?: string | null;
  authProvider?: ('password' | 'phone' | 'yandex') | null;
  yandexId?: string | null;
  favorites?: (number | Product)[] | null;
  consentPdAt?: string | null;
  b24CompanyId?: string | null;
  b24ContactId?: string | null;
  onecId?: string | null;
  syncError?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * Латиница, цифры и дефис, например feniks-nitril. На сайте: /product/<slug>
   */
  slug: string;
  sku: string;
  category: number | Category;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  base?: string | null;
  coating?: string | null;
  coatingType?: string | null;
  colors?: string[] | null;
  sizes?: string[] | null;
  knitClass?: string | null;
  tex?: string | null;
  weight?: string | null;
  length?: string | null;
  specs?:
    | {
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  documents?:
    | {
        title: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  price?: number | null;
  stock?: number | null;
  unit?: string | null;
  minQty?: number | null;
  packSizes?: number[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  badges?: ('hit' | 'new' | 'sale' | 'home')[] | null;
  guid1c?: string | null;
  manualOverride?: boolean | null;
  related?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * Латиница, цифры и дефис, например feniks-nitril.
   */
  slug: string;
  short?: string | null;
  description?: string | null;
  parent?: (number | null) | Category;
  icon?: string | null;
  image?: (number | null) | Media;
  order?: number | null;
  guid1c?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  title?: string | null;
  kind?: ('image' | 'doc') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  product: number | Product;
  authorName: string;
  company?: string | null;
  city?: string | null;
  rating: number;
  text: string;
  colorLabel?: string | null;
  sizeLabel?: string | null;
  orderDate?: string | null;
  shipped?: boolean | null;
  shippedAt?: string | null;
  recommends?: boolean | null;
  tags?: ('quality' | 'shipment' | 'grip' | 'size' | 'pack')[] | null;
  customer?: (number | null) | Customer;
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  number: string;
  customer?: (number | null) | Customer;
  guest?: {
    name?: string | null;
    phone?: string | null;
    email?: string | null;
    company?: string | null;
    inn?: string | null;
    kpp?: string | null;
  };
  /**
   * Названия и цены зафиксированы на момент оформления и не меняются вслед за каталогом.
   */
  items: {
    product?: (number | null) | Product;
    sku?: string | null;
    title: string;
    size?: string | null;
    coating?: string | null;
    price: number;
    qty: number;
    id?: string | null;
  }[];
  total?: number | null;
  delivery?: {
    city?: string | null;
    carrier?: ('cdek' | 'terminal' | 'pickup') | null;
    carrierName?: string | null;
    cost?: number | null;
    address?: string | null;
  };
  comment?: string | null;
  paymentMethod: 'invoice_auto' | 'invoice_manager' | 'online';
  paymentStatus?: ('pending' | 'invoiced' | 'paid' | 'failed') | null;
  status: 'accepted' | 'picking' | 'shipped' | 'delivery' | 'delivered' | 'cancelled';
  statusHistory?:
    | {
        at?: string | null;
        status?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  consentPdAt?: string | null;
  paymentId?: string | null;
  onecExportedAt?: string | null;
  b24DealId?: string | null;
  syncError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  type: 'feedback' | 'calculation' | 'samples' | 'consultation' | 'product-request' | 'pricelist' | 'cart';
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  company?: string | null;
  message?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  consentPdAt: string;
  sourceUrl?: string | null;
  status?: ('new' | 'processed') | null;
  b24LeadId?: string | null;
  syncError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories".
 */
export interface PostCategory {
  id: number;
  title: string;
  /**
   * Латиница, цифры и дефис, например feniks-nitril.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Латиница, цифры и дефис, например feniks-nitril. На сайте: /blog/<slug>
   */
  slug: string;
  category?: (number | null) | PostCategory;
  /**
   * На витрине показывается целиком (contain), без обрезки — загружайте в исходных пропорциях.
   */
  cover?: (number | null) | Media;
  excerpt: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  slides?:
    | {
        image: number | Media;
        title?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  related?: (number | Post)[] | null;
  publishedAt?: string | null;
  home?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Латиница, цифры и дефис, например feniks-nitril.
   */
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'b24-sync';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'b24-sync') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'post-categories';
        value: number | PostCategory;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  kind?: T;
  name?: T;
  phone?: T;
  company?: T;
  inn?: T;
  kpp?: T;
  address?: T;
  addresses?:
    | T
    | {
        label?: T;
        city?: T;
        line?: T;
        phone?: T;
        isDefault?: T;
        id?: T;
      };
  bankName?: T;
  bankAccount?: T;
  bik?: T;
  authProvider?: T;
  yandexId?: T;
  favorites?: T;
  consentPdAt?: T;
  b24CompanyId?: T;
  b24ContactId?: T;
  onecId?: T;
  syncError?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  short?: T;
  description?: T;
  parent?: T;
  icon?: T;
  image?: T;
  order?: T;
  guid1c?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  sku?: T;
  category?: T;
  description?: T;
  base?: T;
  coating?: T;
  coatingType?: T;
  colors?: T;
  sizes?: T;
  knitClass?: T;
  tex?: T;
  weight?: T;
  length?: T;
  specs?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        title?: T;
        file?: T;
        id?: T;
      };
  price?: T;
  stock?: T;
  unit?: T;
  minQty?: T;
  packSizes?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  badges?: T;
  guid1c?: T;
  manualOverride?: T;
  related?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  title?: T;
  kind?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  authorName?: T;
  company?: T;
  city?: T;
  rating?: T;
  text?: T;
  colorLabel?: T;
  sizeLabel?: T;
  orderDate?: T;
  shipped?: T;
  shippedAt?: T;
  recommends?: T;
  tags?: T;
  customer?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  number?: T;
  customer?: T;
  guest?:
    | T
    | {
        name?: T;
        phone?: T;
        email?: T;
        company?: T;
        inn?: T;
        kpp?: T;
      };
  items?:
    | T
    | {
        product?: T;
        sku?: T;
        title?: T;
        size?: T;
        coating?: T;
        price?: T;
        qty?: T;
        id?: T;
      };
  total?: T;
  delivery?:
    | T
    | {
        city?: T;
        carrier?: T;
        carrierName?: T;
        cost?: T;
        address?: T;
      };
  comment?: T;
  paymentMethod?: T;
  paymentStatus?: T;
  status?: T;
  statusHistory?:
    | T
    | {
        at?: T;
        status?: T;
        note?: T;
        id?: T;
      };
  consentPdAt?: T;
  paymentId?: T;
  onecExportedAt?: T;
  b24DealId?: T;
  syncError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  phone?: T;
  email?: T;
  company?: T;
  message?: T;
  data?: T;
  consentPdAt?: T;
  sourceUrl?: T;
  status?: T;
  b24LeadId?: T;
  syncError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-categories_select".
 */
export interface PostCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  cover?: T;
  excerpt?: T;
  content?: T;
  slides?:
    | T
    | {
        image?: T;
        title?: T;
        alt?: T;
        id?: T;
      };
  related?: T;
  publishedAt?: T;
  home?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Каждая строка — отдельная строка заголовка. Пусто — на сайте текст по умолчанию.
   */
  heroTitle?: string | null;
  /**
   * Пусто — на сайте текст по умолчанию.
   */
  heroText?: string | null;
  stats?:
    | {
        value: number;
        suffix?: string | null;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Пусто — на сайте текст по умолчанию.
   */
  aboutTitle?: string | null;
  /**
   * Пусто — на сайте текст по умолчанию.
   */
  aboutText?: string | null;
  advantages?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  terms?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Пусто — на сайте текст по умолчанию.
   */
  reviewsTitle?: string | null;
  reviews?:
    | {
        company: string;
        city?: string | null;
        line?: string | null;
        text: string;
        fact?: string | null;
        id?: string | null;
      }[]
    | null;
  stamps?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Пусто — на сайте текст по умолчанию.
   */
  ctaTitle?: string | null;
  /**
   * Пусто — на сайте текст по умолчанию.
   */
  ctaText?: string | null;
  /**
   * Пусто — товары с бейджем «На главной».
   */
  featuredProducts?: (number | Product)[] | null;
  /**
   * Пусто — статьи с флагом «Показывать на главной».
   */
  featuredPosts?: (number | Post)[] | null;
  banners?:
    | {
        title: string;
        text?: string | null;
        image?: (number | null) | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Первый абзац — под заголовком «Как устроен цех», остальные — мелким текстом ниже. Пусто — на сайте значение по умолчанию.
   */
  text?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Пусто — на сайте значение по умолчанию.
   */
  capacity?: number | null;
  whyLead?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Пусто — на сайте значение по умолчанию.
   */
  modelsCount?: number | null;
  /**
   * Пусто — на сайте значение по умолчанию.
   */
  regions?: number | null;
  geo?:
    | {
        title: string;
        detail: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Блок «Документы к партии». Пусто — документы по умолчанию.
   */
  documents?:
    | {
        title: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  workshopVideo?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery".
 */
export interface Delivery {
  id: number;
  /**
   * Пусто — текст по умолчанию.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  terms?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  footer?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  contacts?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    /**
     * Только https://…
     */
    max?: string | null;
    hours?: string | null;
    /**
     * Пусто — отделы по умолчанию.
     */
    desks?:
      | {
          title: string;
          phone?: string | null;
          email: string;
          id?: string | null;
        }[]
      | null;
  };
  requisites?: {
    legalName?: string | null;
    inn?: string | null;
    kpp?: string | null;
    ogrn?: string | null;
    bankName?: string | null;
    bankAccount?: string | null;
    corrAccount?: string | null;
    bik?: string | null;
  };
  analytics?: {
    /**
     * Номер счётчика (только цифры). Пусто — счётчик на сайте не подключается.
     */
    yandexMetrika?: string | null;
    /**
     * Пока не подключается: нужно решение по 152-ФЗ (BIZ-3).
     */
    googleAnalytics?: string | null;
  };
  /**
   * ID стадии сделки из Б24 (STAGE_ID). Несопоставленная стадия заказ не меняет.
   */
  b24StageMap?:
    | {
        stage: string;
        status: 'accepted' | 'picking' | 'shipped' | 'delivery' | 'delivered' | 'cancelled';
        /**
         * Пусто — статус оплаты заказа не меняется.
         */
        paymentStatus?: ('pending' | 'invoiced' | 'paid' | 'failed') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroTitle?: T;
  heroText?: T;
  stats?:
    | T
    | {
        value?: T;
        suffix?: T;
        label?: T;
        id?: T;
      };
  aboutTitle?: T;
  aboutText?: T;
  advantages?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  terms?:
    | T
    | {
        text?: T;
        id?: T;
      };
  reviewsTitle?: T;
  reviews?:
    | T
    | {
        company?: T;
        city?: T;
        line?: T;
        text?: T;
        fact?: T;
        id?: T;
      };
  stamps?:
    | T
    | {
        label?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaText?: T;
  featuredProducts?: T;
  featuredPosts?: T;
  banners?:
    | T
    | {
        title?: T;
        text?: T;
        image?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  text?: T;
  capacity?: T;
  whyLead?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  modelsCount?: T;
  regions?: T;
  geo?:
    | T
    | {
        title?: T;
        detail?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        title?: T;
        file?: T;
        id?: T;
      };
  workshopVideo?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery_select".
 */
export interface DeliverySelect<T extends boolean = true> {
  intro?: T;
  terms?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  contacts?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        max?: T;
        hours?: T;
        desks?:
          | T
          | {
              title?: T;
              phone?: T;
              email?: T;
              id?: T;
            };
      };
  requisites?:
    | T
    | {
        legalName?: T;
        inn?: T;
        kpp?: T;
        ogrn?: T;
        bankName?: T;
        bankAccount?: T;
        corrAccount?: T;
        bik?: T;
      };
  analytics?:
    | T
    | {
        yandexMetrika?: T;
        googleAnalytics?: T;
      };
  b24StageMap?:
    | T
    | {
        stage?: T;
        status?: T;
        paymentStatus?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskB24-sync".
 */
export interface TaskB24Sync {
  input: {
    kind: 'order' | 'lead' | 'company';
    id: string;
  };
  output: {
    status: string;
    b24Id?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}